media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title ]
    fields:
      - name: layout
        label: Layout
        type: string
        default: event
      - name: title
        label: Title
        type: string