media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title ]
    fields:
      - name: layout
        label: Layout
        type: string
        default: event
      - name: category
        label: Category
        type: string
        default: events
      - name: title
        label: Title
        type: string
      - name: date
        label: Event Date
        type: date
        options:
          format: yyyy/mm/dd