media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, date, datestart, location, hosts ]
    fields:
      - name: layout
        label: Layout
        type: string
        default: event
      - name: category
        label: Category
        type: string
        default: events
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Post Date
        description: Date when the post was created (i.e. today's date)
        type: date
        options:
          format: yyyy/MM/dd
        required: true
      - name: datestart
        label: Event Start Date
        type: date
        description: Event's start date (i.e. some future fate)
        options:
          format: yyyy/MM/dd
        required: true
      - name: location
        label: Location
        type: string
        description: Street address of the event. Be sure to include the country. (e.g. 123 Abc Drive, New York, NY 10001, United States).
      - name: hosts
        label: Hosts
        type: string
        description: Names of who are performing at the event
        list: true
      - name: tickets
        label: Tickets URL
        type: string
        description: URL for the website to get the tickets from
      - name: facebook
        label: Facebook URL
        type: string
        description: URL of the Facebook page that has more info about the event
      - name: image
        label: Image Path
        type: string
        description: Path to the image for the event (e.g. `/assets/img/events/….jpg`)
        pattern: \/assets\/img\/events\/.+\.jpg